name: remind

on:
  schedule:
    # - cron: '0 15 1 * *'
    - cron: '*/5 * * * *'  # for test

jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ':bell: Confirmation of VSCode config :bell:'
          SLACK_MESSAGE: 'Please update if you add other extensions or configures.\nhttps://github.com/masahito1997/vscode_config'
